package com.webapp.project.modules.feetype.model;
// Generated Apr 3, 2017 12:57:15 PM by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Feetypes generated by hbm2java
 */
@Entity
@Table(name = "feetypes", catalog = "webapp")
public class FeeType implements java.io.Serializable {

	private Integer feetypesId;
	private String feetypes;
	private String note;

	public FeeType() {
	}

	public FeeType(String feetypes) {
		this.feetypes = feetypes;
	}

	public FeeType(String feetypes, String note) {
		this.feetypes = feetypes;
		this.note = note;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "feetypesID", unique = true, nullable = false)
	public Integer getFeetypesId() {
		return this.feetypesId;
	}

	public void setFeetypesId(Integer feetypesId) {
		this.feetypesId = feetypesId;
	}

	@Column(name = "feetypes", nullable = false, length = 60)
	public String getFeetypes() {
		return this.feetypes;
	}

	public void setFeetypes(String feetypes) {
		this.feetypes = feetypes;
	}

	@Column(name = "note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
