package com.webapp.project.modules.expense.model;
// Generated Apr 3, 2017 12:57:15 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Expense generated by hbm2java
 */
@Entity
@Table(name = "expense", catalog = "webapp")
public class Expense implements java.io.Serializable {

	private Integer expenseId;
	private Date date;
	private String expenseday;
	private String expensemonth;
	private Date expenseyear;
	private String expense;
	private double amount;
	private int userId;
	private int usertypeId;
	private String uname;
	private int schoolyearId;
	private Date createDate;
	private Date modifyDate;
	private int createUserId;
	private String createUsername;
	private String createUsertype;
	private String note;

	public Expense() {
	}

	public Expense(Date date, String expenseday, String expensemonth, Date expenseyear, String expense, double amount,
			int userId, int usertypeId, String uname, int schoolyearId, Date createDate, Date modifyDate,
			int createUserId, String createUsername, String createUsertype) {
		this.date = date;
		this.expenseday = expenseday;
		this.expensemonth = expensemonth;
		this.expenseyear = expenseyear;
		this.expense = expense;
		this.amount = amount;
		this.userId = userId;
		this.usertypeId = usertypeId;
		this.uname = uname;
		this.schoolyearId = schoolyearId;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
		this.createUserId = createUserId;
		this.createUsername = createUsername;
		this.createUsertype = createUsertype;
	}

	public Expense(Date date, String expenseday, String expensemonth, Date expenseyear, String expense, double amount,
			int userId, int usertypeId, String uname, int schoolyearId, Date createDate, Date modifyDate,
			int createUserId, String createUsername, String createUsertype, String note) {
		this.date = date;
		this.expenseday = expenseday;
		this.expensemonth = expensemonth;
		this.expenseyear = expenseyear;
		this.expense = expense;
		this.amount = amount;
		this.userId = userId;
		this.usertypeId = usertypeId;
		this.uname = uname;
		this.schoolyearId = schoolyearId;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
		this.createUserId = createUserId;
		this.createUsername = createUsername;
		this.createUsertype = createUsertype;
		this.note = note;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "expenseID", unique = true, nullable = false)
	public Integer getExpenseId() {
		return this.expenseId;
	}

	public void setExpenseId(Integer expenseId) {
		this.expenseId = expenseId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "expenseday", nullable = false, length = 11)
	public String getExpenseday() {
		return this.expenseday;
	}

	public void setExpenseday(String expenseday) {
		this.expenseday = expenseday;
	}

	@Column(name = "expensemonth", nullable = false, length = 11)
	public String getExpensemonth() {
		return this.expensemonth;
	}

	public void setExpensemonth(String expensemonth) {
		this.expensemonth = expensemonth;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "expenseyear", nullable = false, length = 0)
	public Date getExpenseyear() {
		return this.expenseyear;
	}

	public void setExpenseyear(Date expenseyear) {
		this.expenseyear = expenseyear;
	}

	@Column(name = "expense", nullable = false, length = 128)
	public String getExpense() {
		return this.expense;
	}

	public void setExpense(String expense) {
		this.expense = expense;
	}

	@Column(name = "amount", nullable = false, precision = 22, scale = 0)
	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	@Column(name = "userID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "usertypeID", nullable = false)
	public int getUsertypeId() {
		return this.usertypeId;
	}

	public void setUsertypeId(int usertypeId) {
		this.usertypeId = usertypeId;
	}

	@Column(name = "uname", nullable = false, length = 40)
	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	@Column(name = "schoolyearID", nullable = false)
	public int getSchoolyearId() {
		return this.schoolyearId;
	}

	public void setSchoolyearId(int schoolyearId) {
		this.schoolyearId = schoolyearId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_date", nullable = false, length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "create_userID", nullable = false)
	public int getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(int createUserId) {
		this.createUserId = createUserId;
	}

	@Column(name = "create_username", nullable = false, length = 40)
	public String getCreateUsername() {
		return this.createUsername;
	}

	public void setCreateUsername(String createUsername) {
		this.createUsername = createUsername;
	}

	@Column(name = "create_usertype", nullable = false, length = 20)
	public String getCreateUsertype() {
		return this.createUsertype;
	}

	public void setCreateUsertype(String createUsertype) {
		this.createUsertype = createUsertype;
	}

	@Column(name = "note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
